---
- name: Init git username
  command: git config --global user.name "{{ git_user }}"

- name: Init git email
  command: git config --global user.email "{{ git_email }}"

- name: "Create an ./src dir"
  file:
    path: ./src
    state: directory
    mode: '0755'
