- name: "Clean-up old docker versions"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: "apt: install docker prerequisites"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present  

- name: "Add docker apt repository key"
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: "Add apt docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present

- name: "apt update: post docker repository add"
  apt:
    update_cache: yes
    
- name: "apt install docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present  

- name: "Add the user 'admin' to 'docker' group"
  user:
    name: admin
    groups: docker
    append: yes

- name: "Set systemd defaults"
  template:
    src: templates/daemon.j2
    dest: "/etc/docker/daemon.json"

- name: "Create docker systemd directory"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: "Start docker service"
  systemd:
    state: started
    daemon_reload: yes
    name: docker
