---
- name: "Create a /etc/kubernetes"
  file:
    path: /etc/kubernetes
    state: directory
    mode: '0755'
- name: "fetch /etc/kubernetes/admin.conf"
  copy:
    src: ./stage_output/admin.conf
    dest: /etc/kubernetes/admin.conf
    owner: root
    group: root
    mode: '0644'  
- name: "fetch /etc/kubernetes/controller-manager.conf"
  copy:
    src: ./stage_output/controller-manager.conf
    dest: /etc/kubernetes/controller-manager.conf
    owner: root
    group: root
    mode: '0644'  
# - name: "fetch /etc/kubernetes/kubelet.conf"
#   copy:
#     src: ./stage_output/kubelet.conf
#     dest: /etc/kubernetes/kubelet.conf
#     owner: root
#     group: root
#     mode: '0644'  
- name: "fetch /etc/kubernetes/scheduler.conf"
  copy:
    src: ./stage_output/scheduler.conf
    dest: /etc/kubernetes/scheduler.conf
    owner: root
    group: root
    mode: '0644'
# - name: "Create a /etc/kubernetes/manifests"
#   file:
#     path: /etc/kubernetes/manifests
#     state: directory
#     mode: '0755'
# - name: "fetch /etc/kubernetes/manifests/etcd.yaml"
#   copy:
#     src: ./stage_output/manifests/etcd.yaml
#     dest: /etc/kubernetes/manifests/etcd.yaml
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/manifests/kube-apiserver.yaml"
#   copy:
#     src: ./stage_output/manifests/kube-apiserver.yaml
#     dest: /etc/kubernetes/manifests/kube-apiserver.yaml
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/manifests/kube-controller-manager.yaml"
#   copy:
#     src: ./stage_output/manifests/kube-controller-manager.yaml
#     dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/manifests/kube-scheduler.yaml"
#   copy:
#     src: ./stage_output/manifests/kube-scheduler.yaml
#     dest: /etc/kubernetes/manifests/kube-scheduler.yaml
#     owner: root
#     group: root
#     mode: '0644'
- name: "Create a /etc/kubernetes/pki"
  file:
    path: /etc/kubernetes/pki
    state: directory
    mode: '0755'
- name: "fetch /etc/kubernetes/pki/apiserver-etcd-client.crt"
  copy:
    src: ./stage_output/pki/apiserver-etcd-client.crt
    dest: /etc/kubernetes/pki/apiserver-etcd-client.crt
    owner: root
    group: root
    mode: '0644'  
- name: "fetch /etc/kubernetes/pki/apiserver-etcd-client.key"
  copy:
    src: ./stage_output/pki/apiserver-etcd-client.key
    dest: /etc/kubernetes/pki/apiserver-etcd-client.key
    owner: root
    group: root
    mode: '0644'  
- name: "fetch /etc/kubernetes/pki/apiserver-kubelet-client.crt"
  copy:
    src: ./stage_output/pki/apiserver-kubelet-client.crt
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.crt
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/apiserver-kubelet-client.key"
  copy:
    src: ./stage_output/pki/apiserver-kubelet-client.key
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.key
    owner: root
    group: root
    mode: '0644'
# - name: "fetch /etc/kubernetes/pki/apiserver.crt"
#   copy:
#     src: ./stage_output/pki/apiserver.crt
#     dest: /etc/kubernetes/pki/apiserver.crt
#     owner: root
#     group: root
#     mode: '0644'
# - name: "fetch /etc/kubernetes/pki/apiserver.key"
#   copy:
#     src: ./stage_output/pki/apiserver.key
#     dest: /etc/kubernetes/pki/apiserver.key
#     owner: root
#     group: root
#     mode: '0644'
- name: "fetch /etc/kubernetes/pki/ca.crt"
  copy:
    src: ./stage_output/pki/ca.crt
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/ca.key"
  copy:
    src: ./stage_output/pki/ca.key
    dest: /etc/kubernetes/pki/ca.key
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/front-proxy-ca.crt"
  copy:
    src: ./stage_output/pki/front-proxy-ca.crt
    dest: /etc/kubernetes/pki/front-proxy-ca.crt
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/front-proxy-ca.key"
  copy:
    src: ./stage_output/pki/front-proxy-ca.key
    dest: /etc/kubernetes/pki/front-proxy-ca.key
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/front-proxy-client.crt"
  copy:
    src: ./stage_output/pki/front-proxy-client.crt
    dest: /etc/kubernetes/pki/front-proxy-client.crt
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/front-proxy-cclient.key"
  copy:
    src: ./stage_output/pki/front-proxy-client.key
    dest: /etc/kubernetes/pki/front-proxy-client.key
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/sa.pub"
  copy:
    src: ./stage_output/pki/sa.pub
    dest: /etc/kubernetes/pki/sa.pub
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/sa.key"
  copy:
    src: ./stage_output/pki/sa.key
    dest: /etc/kubernetes/pki/sa.key
    owner: root
    group: root
    mode: '0644'
- name: "Create a /etc/kubernetes/pki/etcd"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    mode: '0755'
- name: "fetch /etc/kubernetes/pki/etcd/ca.crt"
  copy:
    src: ./stage_output/pki/etcd/ca.crt
    dest: /etc/kubernetes/pki/etcd/ca.crt
    owner: root
    group: root
    mode: '0644'
- name: "fetch /etc/kubernetes/pki/etcd/ca.key"
  copy:
    src: ./stage_output/pki/etcd/ca.key
    dest: /etc/kubernetes/pki/etcd/ca.key
    owner: root
    group: root
    mode: '0644'  
# - name: "fetch /etc/kubernetes/pki/etcd/healthcheck-client.crt"
#   copy:
#     src: ./stage_output/pki/etcd/healthcheck-client.crt
#     dest: /etc/kubernetes/pki/etcd/healthcheck-client.crt
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/pki/etcd/healthcheck-client.key"
#   copy:
#     src: ./stage_output/pki/etcd/healthcheck-client.key
#     dest: /etc/kubernetes/pki/etcd/healthcheck-client.key
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/pki/etcd/peer.crt"
#   copy:
#     src: ./stage_output/pki/etcd/peer.crt
#     dest: /etc/kubernetes/pki/etcd/peer.crt
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/pki/etcd/peer.key"
#   copy:
#     src: ./stage_output/pki/etcd/peer.key
#     dest: /etc/kubernetes/pki/etcd/peer.key
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/pki/etcd/server.crt"
#   copy:
#     src: ./stage_output/pki/etcd/server.crt
#     dest: /etc/kubernetes/pki/etcd/server.crt
#     owner: root
#     group: root
#     mode: '0644'  
# - name: "fetch /etc/kubernetes/pki/etcd/server.key"
#   copy:
#     src: ./stage_output/pki/etcd/server.key
#     dest: /etc/kubernetes/pki/etcd/server.key
#     owner: root
#     group: root
#     mode: '0644'  
