- name: "Create a /home/admin/auth"
  file:
    path: /home/admin/auth
    state: directory
    mode: '0755'

- name: example copying file with owner and permissions
  copy:
    src: /home/admin/shadow/htpasswd
    dest: /home/admin/auth/htpasswd
    owner: admin
    group: admin
    mode: 0644
    
#- name: "Generate auth"
#  shell: docker run --entrypoint htpasswd registry:2 -Bbn admin admin > /home/admin/auth/htpasswd

- name: "Create a /mnt/registry"
  file:
    path: /mnt/registry
    state: directory
    mode: '0755'

- name: "Run registry"
  shell: 'docker run -d \
  -p 5000:5000 \
  --restart=always \
  --name registry \
  --network host \
  -v /admin/auth:/auth \
  -v /mnt/registry:/var/lib/registry \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e "REGISTRY_HTTP_SECRET=constantrandomsecret" \
  -e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" \
  registry:2'
