---
version: "3.7"
services:
 vpn:
  image: infra:latest
  user: "${UID}:${GID}"
  container_name: tools
  privileged: true
  dns:
   - 169.254.169.254
   - 8.8.4.4
   - 2001:4860:4860::8844
  tty: true
  devices:
   - /dev/net/tun:/dev/net/tun
  volumes:
   - ${HOME}/src:/home/admin/src:z
   - ${HOME}/shadow:/home/admin/shadow:z
# Uncomment if you prefer to use emacs as editor.
# Make sure ${HOME}/.emacs.d exists.
   - ${HOME}/.emacs.d:/home/admin/.emacs.d:z  
   - ${XAUTHORITY}:/home/admin/.Xauthority
   - /tmp/.X11-unix:/tmp/.X11-unix  
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  network_mode: bridge
  restart: unless-stopped
  cap_add:
   - NET_ADMIN
   - SYS_MODULE
  environment:
   - IPTABLES_MASQ=1
   - DISPLAY=:0
