---
version: "3.7"
services:
 vpn:
  image: infra:latest
  container_name: tools
  privileged: true
  dns:
   - 169.254.169.254
   - 8.8.4.4
   - 2001:4860:4860::8844
  tty: true
  devices:
   - /dev/net/tun:/dev/net/tun
  volumes:
   - ${HOME}/git/infra:/root/src:z
   - ${HOME}/shadow:/root/shadow:z
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  network_mode: bridge
  restart: unless-stopped
  cap_add:
   - NET_ADMIN
   - SYS_MODULE
  environment:
   - IPTABLES_MASQ=1
